import matplotlib.pyplot as plt

# 1. Read the data generated by Ngspice
gm_values = []
with open('mc_data.txt', 'r') as file:
    for line in file:
        parts = line.strip().split()
        # Ngspice prints data as "Index Value", so we grab the second column
        if len(parts) == 2:
            try:
                gm_values.append(float(parts[1]))
            except ValueError:
                pass

# 2. Draw the Bell Curve / Histogram
# 'bins=10' splits the data into 10 columns. You can increase this for more detail!
plt.hist(gm_values, bins=10, color='royalblue', edgecolor='black', alpha=0.8)

# 3. Add labels
plt.title('Gm Mismatch Distribution (Monte Carlo)')
plt.xlabel('Transconductance (A/V)')
plt.ylabel('Number of Chips')
plt.grid(axis='y', alpha=0.75)

# 4. Show the plot on your remote desktop
plt.show()
